/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    accounts: Account;
    people: Person;
    categories: Category;
    tags: Tag;
    transactions: Transaction;
    'transaction-links': TransactionLink;
    reminders: Reminder;
    'user-settings': UserSetting;
    'ai-usages': AiUsage;
    'oauth-accounts': OauthAccount;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'oauth-codes': OauthCode;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      settings: 'user-settings';
    };
    transactions: {
      outgoingLinks: 'transaction-links';
      incomingLinks: 'transaction-links';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'transaction-links': TransactionLinksSelect<false> | TransactionLinksSelect<true>;
    reminders: RemindersSelect<false> | RemindersSelect<true>;
    'user-settings': UserSettingsSelect<false> | UserSettingsSelect<true>;
    'ai-usages': AiUsagesSelect<false> | AiUsagesSelect<true>;
    'oauth-accounts': OauthAccountsSelect<false> | OauthAccountsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'oauth-codes': OauthCodesSelect<false> | OauthCodesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'app-settings': AppSetting;
  };
  globalsSelect: {
    'app-settings': AppSettingsSelect<false> | AppSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    'dashboard-summary': DashboardSummaryWidget;
    'weekly-expenses': WeeklyExpensesWidget;
    'monthly-calendar': MonthlyCalendarWidget;
    'monthly-categories': MonthlyCategoriesWidget;
    'monthly-tags': MonthlyTagsWidget;
    'monthly-people': MonthlyPeopleWidget;
    reseed: ReseedWidget;
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  avatar?: (string | null) | Media;
  settings?: {
    docs?: (string | UserSetting)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  role?: ('user' | 'admin' | 'system') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  type?: ('avatar' | 'attachment' | 'other') | null;
  entityType?: ('person' | 'account' | 'transaction' | 'other') | null;
  user: string | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-settings".
 */
export interface UserSetting {
  id: string;
  user: string | User;
  currency?: string | null;
  timezone?: string | null;
  locale?: string | null;
  theme?: ('light' | 'dark' | 'system') | null;
  defaultAccount?: (string | null) | Account;
  /**
   * Used for AI features. Stored securely — only the masked value is returned via the API.
   */
  geminiApiKey?: string | null;
  /**
   * Which AI backend powers category suggestions in the transaction form. Local is free and fast; Gemini is slower but more reasoning-aware and counts against the AI quota.
   */
  categoryAiMethod?: ('minilm' | 'gemini') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  user: string | User;
  name: string;
  icon: string;
  bgColor?: string | null;
  color?: string | null;
  avatar?: (string | null) | Media;
  description?: string | null;
  isActive?: boolean | null;
  balance?: number | null;
  totalTransactions?: number | null;
  lastTransactionAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL path for this page (e.g. "privacy-policy" → /pages/privacy-policy)
   */
  slug: string;
  /**
   * Short summary used in meta tags and page listings.
   */
  description?: string | null;
  /**
   * Build the page content using blocks.
   */
  layout: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        style: 'info' | 'warning' | 'success' | 'error';
        content: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'banner';
      }
    | {
        language?: ('bash' | 'json' | 'javascript' | 'typescript' | 'css' | 'text') | null;
        /**
         * Optional label shown above the code block
         */
        caption?: string | null;
        code: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'code';
      }
  )[];
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: string;
  user: string | User;
  name: string;
  email?: string | null;
  phone?: string | null;
  avatar?: (string | null) | Media;
  description?: string | null;
  isActive?: boolean | null;
  balance?: number | null;
  totalTransactions?: number | null;
  lastTransactionAt?: string | null;
  totalSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  user: string | User;
  name: string;
  type: 'income' | 'expense' | 'transfer';
  parent?: (string | null) | Category;
  icon: string;
  color?: string | null;
  bgColor?: string | null;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  user: string | User;
  name: string;
  icon: string;
  color?: string | null;
  bgColor?: string | null;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  user: string | User;
  title: string;
  amount: string;
  date: string;
  type: 'income' | 'expense' | 'transfer';
  category: string | Category;
  account: string | Account;
  /**
   * Destination account for transfers
   */
  toAccount?: (string | null) | Account;
  person?: (string | null) | Person;
  tags?: (string | Tag)[] | null;
  attachments?: (string | Media)[] | null;
  note?: string | null;
  isActive?: boolean | null;
  /**
   * Links where this transaction is the source (e.g. this repaid another)
   */
  outgoingLinks?: {
    docs?: (string | TransactionLink)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Links where this transaction is the target (e.g. others repaid this)
   */
  incomingLinks?: {
    docs?: (string | TransactionLink)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transaction-links".
 */
export interface TransactionLink {
  id: string;
  user: string | User;
  /**
   * The source transaction (the action)
   */
  from: string | Transaction;
  /**
   * The target transaction (the reference)
   */
  to: string | Transaction;
  type: 'repaid' | 'returned' | 'duplicate' | 'correction';
  /**
   * Additional context for this link
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminders".
 */
export interface Reminder {
  id: string;
  user: string | User;
  title: string;
  amount?: string | null;
  type?: ('income' | 'expense' | 'transfer') | null;
  category?: (string | null) | Category;
  account?: (string | null) | Account;
  member?: (string | null) | Person;
  date?: string | null;
  isRecurring?: boolean | null;
  /**
   * How many units between recurrences
   */
  recurrencePeriod?: number | null;
  recurrenceType?: ('daily' | 'weekly' | 'monthly' | 'yearly') | null;
  lastTriggeredAt?: string | null;
  nextDueDate?: string | null;
  tags?: (string | Tag)[] | null;
  completedDates?:
    | {
        date: string;
        id?: string | null;
      }[]
    | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usages".
 */
export interface AiUsage {
  id: string;
  user: string | User;
  promptType: 'text' | 'image' | 'category-suggestion' | 'category-prediction';
  model?: string | null;
  promptTokens?: number | null;
  candidateTokens?: number | null;
  totalTokens?: number | null;
  latencyMs?: number | null;
  status: 'success' | 'error';
  apiKeyType?: ('user' | 'app' | 'local') | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth-accounts".
 */
export interface OauthAccount {
  id: string;
  name?: string | null;
  picture?: string | null;
  user: string | User;
  issuerName: string;
  scope?: string | null;
  sub: string;
  access_token?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  accounts?: {
    /**
     * Allow clients to find accounts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create accounts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update accounts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete accounts.
     */
    delete?: boolean | null;
  };
  people?: {
    /**
     * Allow clients to find people.
     */
    find?: boolean | null;
    /**
     * Allow clients to create people.
     */
    create?: boolean | null;
    /**
     * Allow clients to update people.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete people.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  tags?: {
    /**
     * Allow clients to find tags.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tags.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tags.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tags.
     */
    delete?: boolean | null;
  };
  transactions?: {
    /**
     * Allow clients to find transactions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create transactions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update transactions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete transactions.
     */
    delete?: boolean | null;
  };
  transactionLinks?: {
    /**
     * Allow clients to find transaction-links.
     */
    find?: boolean | null;
    /**
     * Allow clients to create transaction-links.
     */
    create?: boolean | null;
    /**
     * Allow clients to update transaction-links.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete transaction-links.
     */
    delete?: boolean | null;
  };
  reminders?: {
    /**
     * Allow clients to find reminders.
     */
    find?: boolean | null;
    /**
     * Allow clients to create reminders.
     */
    create?: boolean | null;
    /**
     * Allow clients to update reminders.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete reminders.
     */
    delete?: boolean | null;
  };
  userSettings?: {
    /**
     * Allow clients to find user-settings.
     */
    find?: boolean | null;
    /**
     * Allow clients to update user-settings.
     */
    update?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Returns the authenticated user's financial dashboard: total balance across all active accounts, percentage change vs last month's surplus, and current month income/expenses/surplus. Use this to answer questions like 'how am I doing this month?' or 'what is my total balance?'
     */
    getDashboardSummary?: boolean | null;
    /**
     * Returns expense spending grouped by category for a given month, including per-category totals, transaction counts, averages, and parent rollup. Use this to answer questions like 'what did I spend on food this month?' or 'show my top spending categories'.
     */
    getMonthlyCategories?: boolean | null;
    /**
     * Returns transaction activity grouped by tag for a given month, split by expense/income/transfer. Use this to answer questions like 'how much did I spend on subscriptions?' or 'show activity by tag this month'.
     */
    getMonthlyTags?: boolean | null;
    /**
     * Returns the authenticated user's profile (id, email, name, role) and their current settings (currency, timezone, locale, theme). Use this to identify who is connected or to resolve user-specific defaults before making other API calls.
     */
    getCurrentUser?: boolean | null;
    /**
     * Returns monthly transaction activity per person plus their all-time balance. Use this to answer questions like 'how much did I lend to John this month?' or 'who do I owe money to?'.
     */
    getMonthlyPeople?: boolean | null;
  };
  'payload-mcp-resource'?: {
    /**
     * Returns an array of all supported ISO 4217 currency codes (e.g. ["AED", "AFN", "ALL", ...]). Use this to discover available currencies before fetching full metadata via currencies://code/{code}.
     */
    currencies?: boolean | null;
    /**
     * Returns metadata for a single currency by its ISO 4217 code (e.g. USD, EUR, GBP). Includes symbol, native symbol, plural name, decimal digits, and rounding precision.
     */
    currency?: boolean | null;
    /**
     * Returns an array of all supported IANA timezone IDs (e.g. ["Africa/Abidjan", "America/New_York", ...]). Use this to discover available timezones before fetching full metadata via timezones://id/{id}.
     */
    timezones?: boolean | null;
    /**
     * Returns metadata for a single IANA timezone by its ID (e.g. America/New_York, Europe/London). Includes region, city, UTC offset, and display label.
     */
    timezone?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth-codes".
 */
export interface OauthCode {
  id: string;
  code: string;
  clientId: string;
  apiKeyId: string;
  apiKeyValue: string;
  redirectUri: string;
  codeChallenge?: string | null;
  expiresAt: string;
  userId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'people';
        value: string | Person;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'transaction-links';
        value: string | TransactionLink;
      } | null)
    | ({
        relationTo: 'reminders';
        value: string | Reminder;
      } | null)
    | ({
        relationTo: 'user-settings';
        value: string | UserSetting;
      } | null)
    | ({
        relationTo: 'ai-usages';
        value: string | AiUsage;
      } | null)
    | ({
        relationTo: 'oauth-accounts';
        value: string | OauthAccount;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'oauth-codes';
        value: string | OauthCode;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  settings?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  type?: T;
  entityType?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              style?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        code?:
          | T
          | {
              language?: T;
              caption?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  icon?: T;
  bgColor?: T;
  color?: T;
  avatar?: T;
  description?: T;
  isActive?: T;
  balance?: T;
  totalTransactions?: T;
  lastTransactionAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  email?: T;
  phone?: T;
  avatar?: T;
  description?: T;
  isActive?: T;
  balance?: T;
  totalTransactions?: T;
  lastTransactionAt?: T;
  totalSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  type?: T;
  parent?: T;
  icon?: T;
  color?: T;
  bgColor?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  icon?: T;
  color?: T;
  bgColor?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  amount?: T;
  date?: T;
  type?: T;
  category?: T;
  account?: T;
  toAccount?: T;
  person?: T;
  tags?: T;
  attachments?: T;
  note?: T;
  isActive?: T;
  outgoingLinks?: T;
  incomingLinks?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transaction-links_select".
 */
export interface TransactionLinksSelect<T extends boolean = true> {
  user?: T;
  from?: T;
  to?: T;
  type?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminders_select".
 */
export interface RemindersSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  amount?: T;
  type?: T;
  category?: T;
  account?: T;
  member?: T;
  date?: T;
  isRecurring?: T;
  recurrencePeriod?: T;
  recurrenceType?: T;
  lastTriggeredAt?: T;
  nextDueDate?: T;
  tags?: T;
  completedDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-settings_select".
 */
export interface UserSettingsSelect<T extends boolean = true> {
  user?: T;
  currency?: T;
  timezone?: T;
  locale?: T;
  theme?: T;
  defaultAccount?: T;
  geminiApiKey?: T;
  categoryAiMethod?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usages_select".
 */
export interface AiUsagesSelect<T extends boolean = true> {
  user?: T;
  promptType?: T;
  model?: T;
  promptTokens?: T;
  candidateTokens?: T;
  totalTokens?: T;
  latencyMs?: T;
  status?: T;
  apiKeyType?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth-accounts_select".
 */
export interface OauthAccountsSelect<T extends boolean = true> {
  name?: T;
  picture?: T;
  user?: T;
  issuerName?: T;
  scope?: T;
  sub?: T;
  access_token?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  users?:
    | T
    | {
        find?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  accounts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  people?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  tags?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  transactions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  transactionLinks?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  reminders?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  userSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        getDashboardSummary?: T;
        getMonthlyCategories?: T;
        getMonthlyTags?: T;
        getCurrentUser?: T;
        getMonthlyPeople?: T;
      };
  'payload-mcp-resource'?:
    | T
    | {
        currencies?: T;
        currency?: T;
        timezones?: T;
        timezone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth-codes_select".
 */
export interface OauthCodesSelect<T extends boolean = true> {
  code?: T;
  clientId?: T;
  apiKeyId?: T;
  apiKeyValue?: T;
  redirectUri?: T;
  codeChallenge?: T;
  expiresAt?: T;
  userId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings".
 */
export interface AppSetting {
  id: string;
  ai?: {
    /**
     * Master switch for all AI features across the app.
     */
    enabled?: boolean | null;
    /**
     * App-level Gemini API key. Used as fallback when a user has no personal key configured.
     */
    geminiApiKey?: string | null;
    /**
     * When enabled, users with their own Gemini API key will use it instead of the app key.
     */
    allowUserApiKey?: boolean | null;
    /**
     * Model used when no model is specified in the request.
     */
    defaultModel?: string | null;
    /**
     * List of model IDs clients can choose from. Leave empty to allow any model.
     */
    models?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Maximum AI requests per user per day. Set to 0 for unlimited.
     */
    perUserDailyLimit?: number | null;
    /**
     * Maximum AI requests per user per month. Set to 0 for unlimited.
     */
    perUserMonthlyLimit?: number | null;
    /**
     * Uses a small on-server ML model (transformers.js) to auto-suggest categories as the user types. No external API call.
     */
    predictionEnabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings_select".
 */
export interface AppSettingsSelect<T extends boolean = true> {
  ai?:
    | T
    | {
        enabled?: T;
        geminiApiKey?: T;
        allowUserApiKey?: T;
        defaultModel?: T;
        models?:
          | T
          | {
              name?: T;
              id?: T;
            };
        perUserDailyLimit?: T;
        perUserMonthlyLimit?: T;
        predictionEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard-summary_widget".
 */
export interface DashboardSummaryWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-expenses_widget".
 */
export interface WeeklyExpensesWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-calendar_widget".
 */
export interface MonthlyCalendarWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-categories_widget".
 */
export interface MonthlyCategoriesWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-tags_widget".
 */
export interface MonthlyTagsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-people_widget".
 */
export interface MonthlyPeopleWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseed_widget".
 */
export interface ReseedWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}