/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    accounts: Account;
    people: Person;
    categories: Category;
    tags: Tag;
    transactions: Transaction;
    reminders: Reminder;
    'user-settings': UserSetting;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    reminders: RemindersSelect<false> | RemindersSelect<true>;
    'user-settings': UserSettingsSelect<false> | UserSettingsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    'dashboard-summary': DashboardSummaryWidget;
    'weekly-expenses': WeeklyExpensesWidget;
    'monthly-calendar': MonthlyCalendarWidget;
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  avatar?: (string | null) | Media;
  role?: ('user' | 'admin' | 'system') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  type?: ('avatar' | 'attachment' | 'other') | null;
  entityType?: ('person' | 'account' | 'transaction' | 'other') | null;
  user: string | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  user: string | User;
  name: string;
  icon: string;
  bgColor?: string | null;
  color?: string | null;
  avatar?: (string | null) | Media;
  description?: string | null;
  isActive?: boolean | null;
  balance?: number | null;
  totalTransactions?: number | null;
  lastTransactionAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: string;
  user: string | User;
  name: string;
  email?: string | null;
  phone?: string | null;
  avatar?: (string | null) | Media;
  description?: string | null;
  isActive?: boolean | null;
  balance?: number | null;
  totalTransactions?: number | null;
  lastTransactionAt?: string | null;
  totalSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  user: string | User;
  name: string;
  type: 'income' | 'expense' | 'transfer';
  parent?: (string | null) | Category;
  icon: string;
  color?: string | null;
  bgColor?: string | null;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  user: string | User;
  name: string;
  icon: string;
  color?: string | null;
  bgColor?: string | null;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  user: string | User;
  title: string;
  amount: string;
  date: string;
  type: 'income' | 'expense' | 'transfer';
  category?: (string | null) | Category;
  account: string | Account;
  /**
   * Destination account for transfers
   */
  toAccount?: (string | null) | Account;
  person?: (string | null) | Person;
  tags?: (string | Tag)[] | null;
  attachments?: (string | Media)[] | null;
  note?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminders".
 */
export interface Reminder {
  id: string;
  user: string | User;
  title: string;
  amount?: string | null;
  type?: ('income' | 'expense' | 'transfer') | null;
  category?: (string | null) | Category;
  account?: (string | null) | Account;
  member?: (string | null) | Person;
  date?: string | null;
  isRecurring?: boolean | null;
  /**
   * How many units between recurrences
   */
  recurrencePeriod?: number | null;
  recurrenceType?: ('daily' | 'weekly' | 'monthly' | 'yearly') | null;
  lastTriggeredAt?: string | null;
  nextDueDate?: string | null;
  tags?: (string | Tag)[] | null;
  completedDates?:
    | {
        date: string;
        id?: string | null;
      }[]
    | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-settings".
 */
export interface UserSetting {
  id: string;
  user: string | User;
  currency?: string | null;
  timezone?: string | null;
  locale?: string | null;
  theme?: ('light' | 'dark' | 'system') | null;
  defaultAccount?: (string | null) | Account;
  /**
   * Used for AI features. Stored securely — only the masked value is returned via the API.
   */
  geminiApiKey?: string | null;
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  accounts?: {
    /**
     * Allow clients to find accounts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create accounts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update accounts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete accounts.
     */
    delete?: boolean | null;
  };
  people?: {
    /**
     * Allow clients to find people.
     */
    find?: boolean | null;
    /**
     * Allow clients to create people.
     */
    create?: boolean | null;
    /**
     * Allow clients to update people.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete people.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  tags?: {
    /**
     * Allow clients to find tags.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tags.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tags.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tags.
     */
    delete?: boolean | null;
  };
  transactions?: {
    /**
     * Allow clients to find transactions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create transactions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update transactions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete transactions.
     */
    delete?: boolean | null;
  };
  reminders?: {
    /**
     * Allow clients to find reminders.
     */
    find?: boolean | null;
    /**
     * Allow clients to create reminders.
     */
    create?: boolean | null;
    /**
     * Allow clients to update reminders.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete reminders.
     */
    delete?: boolean | null;
  };
  userSettings?: {
    /**
     * Allow clients to find user-settings.
     */
    find?: boolean | null;
    /**
     * Allow clients to update user-settings.
     */
    update?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Returns the authenticated user's financial dashboard: total balance across all active accounts, percentage change vs last month's surplus, and current month income/expenses/surplus. Use this to answer questions like 'how am I doing this month?' or 'what is my total balance?'
     */
    getDashboardSummary?: boolean | null;
  };
  'payload-mcp-resource'?: {
    /**
     * Complete list of supported currencies with their ISO code, symbol, native symbol, plural name, decimal digits, and rounding. Use this to look up currency metadata or present options for user preference selection.
     */
    currencies?: boolean | null;
    /**
     * Returns metadata for a single currency by its ISO 4217 code (e.g. USD, EUR, GBP). Includes symbol, native symbol, plural name, decimal digits, and rounding precision.
     */
    currency?: boolean | null;
    /**
     * Complete list of supported IANA timezones grouped by region with UTC offset and display label. Use this to look up timezone metadata or present options for user preference selection.
     */
    timezones?: boolean | null;
    /**
     * Returns metadata for a single IANA timezone by its ID (e.g. America/New_York, Europe/London). Includes region, city, UTC offset, and display label.
     */
    timezone?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'people';
        value: string | Person;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'reminders';
        value: string | Reminder;
      } | null)
    | ({
        relationTo: 'user-settings';
        value: string | UserSetting;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  type?: T;
  entityType?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  icon?: T;
  bgColor?: T;
  color?: T;
  avatar?: T;
  description?: T;
  isActive?: T;
  balance?: T;
  totalTransactions?: T;
  lastTransactionAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  email?: T;
  phone?: T;
  avatar?: T;
  description?: T;
  isActive?: T;
  balance?: T;
  totalTransactions?: T;
  lastTransactionAt?: T;
  totalSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  type?: T;
  parent?: T;
  icon?: T;
  color?: T;
  bgColor?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  icon?: T;
  color?: T;
  bgColor?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  amount?: T;
  date?: T;
  type?: T;
  category?: T;
  account?: T;
  toAccount?: T;
  person?: T;
  tags?: T;
  attachments?: T;
  note?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminders_select".
 */
export interface RemindersSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  amount?: T;
  type?: T;
  category?: T;
  account?: T;
  member?: T;
  date?: T;
  isRecurring?: T;
  recurrencePeriod?: T;
  recurrenceType?: T;
  lastTriggeredAt?: T;
  nextDueDate?: T;
  tags?: T;
  completedDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-settings_select".
 */
export interface UserSettingsSelect<T extends boolean = true> {
  user?: T;
  currency?: T;
  timezone?: T;
  locale?: T;
  theme?: T;
  defaultAccount?: T;
  geminiApiKey?: T;
  settings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  users?:
    | T
    | {
        find?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  accounts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  people?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  tags?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  transactions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  reminders?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  userSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        getDashboardSummary?: T;
      };
  'payload-mcp-resource'?:
    | T
    | {
        currencies?: T;
        currency?: T;
        timezones?: T;
        timezone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard-summary_widget".
 */
export interface DashboardSummaryWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-expenses_widget".
 */
export interface WeeklyExpensesWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-calendar_widget".
 */
export interface MonthlyCalendarWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}